version: '3'
services:
  flask:
    build: .
    ports:
      - '5001-5003:5000'
    expose:
      - '5000'
    environment:
      - HOST=0.0.0.0
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      flask_app:
        aliases:
          - flask
    command: python app.py
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    ports:
      - '4000:4000'
    networks:
      flask_app:
        aliases:
          - nginx

networks:
  flask_app:
